### ISSUE TITLE
Bloom release

### ISSUE THREAD

**Issue by Timple** [tilk/rtcm_msgs#1]
Can this message be released to the ros buildfarm for ROS melodic and noetic?

It's an hours work or so: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

I can do the effort if you like.

**Comment by tilk** [comment]
If it's useful for someone - please do.

**Comment by Timple** [comment]
Alright, would you be willing to add a `1.0.0` tag to the first commit?

**Comment by tilk** [comment]
Done.

**Comment by Timple** [comment]
https://github.com/ros/rosdistro/pull/30334
https://github.com/ros/rosdistro/pull/30335

**Comment by Timple** [comment]
Would you mind adding a LICENSE file so others know they may use this code?
https://github.com/ros/rosdistro/pull/30334#pullrequestreview-715139089

I would propose a BSD license as that is what most ROS core components use.

**Comment by tilk** [comment]
Done.

**Comment by Timple** [comment]
Awesome, thank you for being responsive!

**Comment by Timple** [comment]
Released, thank you!
